version: '3.8'

services:
  server:
    image: lazydeveloperakash/bid-backend:latest
    ports:
      - "4006:4006"
    env_file:
      - .env.production
    restart: always

  client:
    image: lazydeveloperakash/bid-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - server
    restart: always