version: '3.8'

services:
  server:
    image: lazydeveloperakash/bid-backend:latest
    ports:
      - "4006:4006"
    env_file:
      - /home/ubuntu/envs/bid-backend.env
    restart: always

  client:
    image: lazydeveloperakash/bid-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - /home/ubuntu/envs/bid-frontend.env
    depends_on:
      - server
    restart: always