name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - "docker-compose.prod.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. Install & Test Frontend
      - name: Install Frontend Dependencies
        working-directory: ./client
        run: npm install

      - name: Frontend Lint
        working-directory: ./client
        run: npm run lint || echo "No lint configured"

      - name: Frontend Test
        working-directory: ./client
        run: npm test || echo "No tests found"

      # 4. Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          docker login \
            -u ${{ secrets.DOCKER_USERNAME }} \
            -p ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build & Push Frontend Image
      - name: Build & Push Frontend Image
        run: |
          docker build \
            -t lazydeveloperakash/bid-frontend:latest \
            -f client/Dockerfile.prod \
            client

          docker push lazydeveloperakash/bid-frontend:latest

  deploy:
    needs: build
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Pull latest frontend image
        run: docker pull lazydeveloperakash/bid-frontend:latest

      - name: Restart frontend container
        run: |
          docker compose -f docker-compose.prod.yml up -d client
